feat(PMF120->PMF140 ILK logic change): PMF 120 is out of commision, changing interlock logic to reflect new physical layout of system
pcdshub/lcls-plc-kfe-gatt pull request #13
Opened 2024-10-16 23:00 UTC by joshc-slac

## Description
PMF 120 failed, had to update interlock logic to reflect new physical configuration in which that which was interlocked to PMF 120 should for now be interlocked to PMF 140. 

## Motivation and Context
![image](https://github.com/user-attachments/assets/4d1d6ff3-9642-4423-bbcb-74b7b8ee0b46)

## How Has This Been Tested?
Needs test

## Where Has This Been Documented?
Needs document

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/18f4d0bc-d140-4ca0-b667-c05db173c2b5)

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

2024-10-16 23:49 UTC, ghalym requested changes

2024-10-16 23:49 UTC, ghalym commented on plc-kfe-gatt/plc_kfe_gatt/POUs/PRG_GATT.TcPOU
> +// temporarily removing interlock logic as PTM 120 has failed and needs to be removed
It is not PTM that has failed. It is the PMF.

2024-10-16 23:49 UTC, ghalym commented on plc-kfe-gatt/plc_kfe_gatt/POUs/PRG_GATT.TcPOU
> +if( fb_AT1K0_GAS_PMF_140.stPump.eState = pumpSTARTING ) OR ( fb_AT1K0_GAS_PMF_120.stPump.eState = pumpRUNNING ) THEN fb_AT1K0_GAS_VVC_120.M_Open(TRUE); END_IF // changed to reflect temporary interloc
This logic still checks the status of PMF 120 = pumpRUNNING, should be PMF140.

2024-10-16 23:50 UTC, ghalym commented on plc-kfe-gatt/plc_kfe_gatt/POUs/PRG_GATT.TcPOU
> +if( fb_AT1K0_GAS_PMF_140.stPump.eState = pumpSTARTING ) OR ( fb_AT1K0_GAS_PMF_120.stPump.eState = pumpRUNNING ) THEN fb_AT1K0_GAS_VVC_120.M_Open(TRUE); END_IF // changed to reflect temporary interloc
on the pydm, the cutoff valve (the tiny icon below the roughing line needs to be relocated as well)

2024-10-16 23:58 UTC, joshc-slac commented on plc-kfe-gatt/plc_kfe_gatt/POUs/PRG_GATT.TcPOU
> +if( fb_AT1K0_GAS_PMF_140.stPump.eState = pumpSTARTING ) OR ( fb_AT1K0_GAS_PMF_120.stPump.eState = pumpRUNNING ) THEN fb_AT1K0_GAS_VVC_120.M_Open(TRUE); END_IF // changed to reflect temporary interloc
Ah, slightly misread intended logic there

2024-10-17 00:41 UTC, ghalym approved these changes
LGTM!

2024-10-17 23:46 UTC, joshc-slac commented
This can be deemed functional. We should monitor this system more closely than normal while its in this off-nominal state

2024-10-17 23:46 UTC, merged